[project]
name = 'edu-tech-integration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.implementation-tracker]
path = 'contracts/implementation-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.technology-assessment]
path = 'contracts/technology-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
